development: &default
  enabled: false
  target: 'dist/scripts'
  repetitive:
    -
      combined: 'combined.js'
      sources:
        - 'dist/scripts/*.js'

test:
  <<: *default

production:
  <<: *default
